---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php support packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"      

#  - name: add php support for apache
#    apt:
#      name: libapache2-mod-php
#      state: absent
#    when: ansible_distribution == "Ubuntu"
