---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
     update_cache: yes
     upgrade: dist

  - name: remove unneeded files
    apt:
      autoremove: yes
      purge: yes
