- name: install applications to configure a jenkins node
  tags: jenkins_config
  apt:
    name:
      - "{{ jdk }}"
    state: latest

- name: create jenkins user
  tags: always
  user:
    name: "{{ jenkins_username }}"
    groups: "{{ jenkins_group }}"
    shell: "{{ jenkins_shell }}"
    home: "{{ jenkins_home_path }}"



