---
# The when condition was added to account for servers that
# such as CenOS or Windows machines that do not use 
# apt has its packaging tool.

- hosts: all
  become: true
  tasks:

  - name: update repository index
    tags: always
    apt:
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    tags: never
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    tags: never
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    tags: never
    yum:
     update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    tags: never
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    tags: never
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
