---

- hosts: all
  become: true
  pre_tasks:
  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu_servers
  become: true
  tasks:
  - name: install apache2, php, tree, htop for Ubuntu servers
    tags: ubuntu_servers,ubuntu_apps
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - tree
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: Centos_servers
  become: true
  tasks:
  - name: install apache, php, tree, epel-release for CentOS servers
    tags: centos_servers,centos_apps
    yum:
      name:
        - httpd
        - php
        - tree
        - epel-release
      state: latest

  - name: make sure httpd service is running
    tags: centos_servers,centos_apps
    ansible.builtin.systemd:
      state: started
      name: httpd
      enabled: yes
      masked: no

  - name: open firewall
    tags: centos_servers,centos_apps
    shell: firewall-cmd --add-service=http --permanent

  - name: restart firewall
    tags: centos_servers,centos_apps
    shell: firewall-cmd --reload

  - name: install htop for CentOS servers
    tags: centos_servers,centos_apps
    yum:
      name:
        - htop
      state: latest

- hosts: all
  become: true
  tasks:
  - name: copy default html file for site
    tags: centos_servers,centos_apps
    copy:
      # The files directory is assumed. Look at ansible documenation to understand that assumption.
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
