---
# The when condition was added to account for servers that
# such as CenOS or Windows machines that do not use 
# apt has its packaging tool.

- hosts: all
  become: true
  tasks:

#  - name: update repository index for Ubuntu
#    apt:
#      update_cache: yes
#      upgrade: dist
#    when: ansible_distribution == "Ubuntu"

#  - name: remove unneeded files
#    apt:
#      autoremove: yes
#      purge: yes
#    when: ansible_distribution == "Ubuntu"

  - name: install apache and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
