---
# The when condition was added to account for servers that
# such as CenOS or Windows machines that do not use 
# apt has its packaging tool.

- hosts: all
  become: true
  pre_tasks:

  - name: insall updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: vm1_server
  tags: apache,apache2,ubuntu
  become: true
  tasks:

  - name: install apache and php package
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      purge: yes

- hosts: vm2_server
  tags: apache,apache2,ubuntu
  become: true
  tasks:

  - name: install googler
    package:
      name:
        - googler
      state: latest
      purge: yes

  - name: install musikcube with snap
    community.general.snap:
      name:
        - musikcube
      state: present
      channel: latest

- hosts: vm3_server
  tags: apache,apache2,ubuntu
  become: true
  tasks:

  - name: install apache and php package for CentOS servers
    tags: apache,centos,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: all
  tags: always
  become: true
  tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      purge: true
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS)
    yum:
      update_only: yes
      update_cache: yes
      autoremove: yes
    when: ansible_distribution == "CentOS"
