---

- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    package:
#     update_cache: yes
#    when: ansible_distribution == "Ubuntu"

  - name: uninstall apache and php support packages for Ubuntu
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
      update_cache: yes
#    when: ansible_distribution == "Ubuntu"      

#  - name: add php support for apache
#    apt:
#      name: libapache2-mod-php
#      state: absent
#    when: ansible_distribution == "Ubuntu"
